global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'accounts-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'accounts-service:8080' ]
  - job_name: 'loans-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'loans-service:8090' ]
  - job_name: 'cards-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'cards-service:9000' ]
  - job_name: 'gateway-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gateway-server:8072' ]
  - job_name: 'eurekaserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eureka-server:8070' ]
  - job_name: 'configserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'config-server:8071' ]
  
