 
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){yellow} %clr(%-5level){blue} %clr([%thread]){magenta} %clr(%logger{36}){cyan} - %msg%n"
 
server:
  port: 8080
spring:
  config:
#    import:
#     - "application_qa.yml"
#     - "application_prod.yml"
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active:
      - "prod"
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
#    driverClassName: org.h2.Driver
    username: root
    password: 1234567
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#  sql:
#    init:
#      mode: always

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
    
    
build:
  version: 3.0

accounts:
  message: "Welcome to Accounts app"
  contactDetails:
    name: John Doe
    email: jhn@example.com
  onCallSupport:
   - 555-555-555
   - 888-888-888


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
   
info:
  app:
    name: "accounts"
    description: "Accounts Application"
    version: "1.0.0"
