version: "3.8"

services:
  rabbit:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - microservice
  
  config-server:
    image: "sayemx/configserver:s6"
    container_name: config-server
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservice
     
  accounts-service:
    image: "sayemx/accounts-service:s6"
    container_name: accounts-service
    ports:
      - "8080:8080"
    depends_on: 
      config-server:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservice
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071/"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_RABBITMQ_HOST: "rabbit"
  
  loans-service:
    image: "sayemx/loans-service:s6"
    container_name: loans-service
    ports:
      - "8090:8090"
    depends_on: 
      config-server:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservice
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071/"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_RABBITMQ_HOST: "rabbit"
      
  cards-service:
    image: "sayemx/cards-service:s6"
    container_name: cards-service
    ports:
      - "9000:9000"
    depends_on: 
      config-server:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservice
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8071/"
      SPRING_PROFILES_ACTIVE: prod
      SPRING_RABBITMQ_HOST: "rabbit"

networks:
  microservice:
    driver: bridge
